# Download immagine base di Node.js
FROM node:24-bookworm-slim

# Imposta la directory di lavoro del container
WORKDIR /usr/app

# Copia il contenuto della root di progetto nella directory di lavoro del container
COPY . .

# Installa dipendenze di progetto
RUN npm install

# Compilazione del progetto
RUN npm run build

# Run di node a patto che si sia avviato PostgreSQL server
CMD ["./wait-for-it.sh", "pa-dbpg-web-node:5432", "-t", "60", "--", "npm", "run", "start"]