export enum AppErrorName {
    INVALID_JWT="INVALID_JWT",
    INVALID_CREDENTIALS="INVALID_CREDENTIALS",
    LOGIN_INVALID="LOGIN_INVALID",
    ROUTE_NOT_FOUND="ROUTE_NOT_FOUND",
    MALFORMED_REQUEST_BODY="MALFORMED_REQUEST_BODY",
    INTERNAL_SERVER_ERROR="INTERNAL_SERVER_ERROR",
    LOGIN_NOT_AVAILABLE = "AUTH_NOT_AVAILABLE",
}