export enum AppErrorMessage {
    INVALID_JWT="Il token di autenticazione non è valido.",
    INVALID_CREDENTIALS="Le credenziali inserite non sono corrette.",
    LOGIN_INVALID="Errore di validazione nella richiesta di login.",
    ROUTE_NOT_FOUND="La rotta richiesta non è stata trovata.",
    MALFORMED_REQUEST_BODY="Non è possibile elaborare il corpo della richiesta.",
    INTERNAL_SERVER_ERROR="Il server non è riuscito a gestire correttamente la richiesta",
    LOGIN_NOT_AVAILABLE = "Errore critico: servizio di login del server non disponibile.",
    UNAUTHORIZED_JWT = "Non sei abilitato a inviare richieste sulla rotta corrente.",
    AUTH_TOKEN_NOTFOUND = "Token mancante nell'header della richiesta.",
    TOKEN_EXPIRED = "Il token utilizzato per l'autenticazione è scaduto.",
    NAVPLAN_REQ_INVALID = "La richiesta di inserimento del piano di navigazione è invalida.",
    NAVPLAN_INVALID = "Il piano di navigazione inserito non è valido.",
    INSUFFICIENT_TOKENS = "Non hai token sufficienti per completare l'operazione richiesta.",
    INVALID_NAVPLAN_DATE = "La data di inizio del piano di navigazione deve essere successiva alla data di invio della richiesta.",
    FORBIDDEN_AREA_ERROR = "Il piano di navigazione attraversa un'area proibita.",
    NAVPLAN_CONFLICT = "Il piano di navigazione proposto è in conflitto con un piano di navigazione già approvato o in attesa di approvazione.",
    FORBIDDEN_NAVPLAN_DELETE = "Non sei autorizzato a cancellare questo piano di navigazione.",
    NAVPLAN_DEL_NOT_FOUND = "Il piano di navigazione richiesto per la cancellazione non è stato trovato.",
    NAVPLAN_DEL_REQ_INVALID = "La richiesta di cancellazione del piano di navigazione è invalida.",
}