export enum AppSuccessName
{
    LOGIN_SUCCESS="LOGIN_SUCCESS",
    NAVPLAN_REQ_CREATED = "NAVPLAN_REQ_CREATED",
    NAVPLAN_REQ_DELETED = "NAVPLAN_REQ_DELETED",
    NAVPLAN_VIEW_SUCCESS = "NAVPLAN_VIEW_SUCCESS"
}