/**
 * Nomi di stati di successo dell'applicazione.
 * Utilizzati da Factory per generare messaggi di successo HTTP corrispondenti.
 */
export enum AppSuccessName
{
    LOGIN_SUCCESS="LOGIN_SUCCESS",
    NAVPLAN_REQ_CREATED = "NAVPLAN_REQ_CREATED",
    NAVPLAN_REQ_DELETED = "NAVPLAN_REQ_DELETED",
    NAVPLAN_VIEW_SUCCESS = "NAVPLAN_VIEW_SUCCESS",
    NONAVZONE_CREATED = "NONAVZONE_CREATED",
    NONAVZONE_UPDATED = "NONAVZONE_UPDATED",
    NONAVZONE_DELETED = "NONAVZONE_DELETED",
    TOKENS_CHARGED_SUCCESSFULLY = "TOKENS_CHARGED_SUCCESSFULLY",
    NAVPLAN_UPDATED = "NAVPLAN_UPDATED"
}